### ISSUE TITLE
用你demo里面那种方法之后，在当前页面怎么关闭全屏右滑返回呢

### ISSUE THREAD

**Issue by BelaW613** [Mrshang110/SGLFullScreenNavigationController#1]
用你demo里面那种方法之后，在当前页面怎么关闭全屏右滑返回呢

**Comment by Mrshang110** [comment]
可以把不需要全屏右滑的加入黑名单,你更新最新代码,可以看下demo

**Comment by BelaW613** [comment]
[((KnmsBaseNavigationController *)self.navigationController) removeFromFullScreenPopBlackList:self];这样调用了没有作用呀，请解答

在 2017-01-22 14:17:14，"尚高林" <notifications@github.com> 写道：


可以把不需要全屏右滑的加入黑名单,你更新最新代码,可以看下demo

**Comment by BelaW613** [comment]
[((KnmsBaseNavigationController *)self.navigationController) removeFromFullScreenPopBlackList:self];在当前页面这样调用了没有作用呀，求解答

**Comment by Mrshang110** [comment]
@BelaW613  应该是添加到黑名单,你这是移除
